-- Add notification settings columns to users table

ALTER TABLE users ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_reminder BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reminder_time VARCHAR(5) DEFAULT '09:00';
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_reminder BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS encouragement BOOLEAN DEFAULT TRUE;
